name: run_get_youtube_data_to_repo
run-name: run_get_youtube_data_to_repo $(date -u)

on:
  workflow_dispatch:

permissions:
  contents:
    write

env:
  TARGET_FILE_PATH: ./backend/pipelines/youtube_api/raw

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5

      - name: install uv project dependencies
        run: |
          uv sync --locked --all-extras --dev

      - name: retrieve API credential
        run: |
          cat ${{ secrets.YOUTUBE_API_CREDENTIAL }} | base64 -d > "$TARGET_FILE_PATH/key.json"

      - name: get data
        run: |
          uv run "$TARGET_FILE_PATH/get_youtube_data_to_repo.py" --key_file_path "$TARGET_FILE_PATH/key.json"

      - name: commit and push
        run: |
          git config --global user.email coffee-operator-github-action@gmail.com
          git config --global user.name coffee-operator-github-action
          git add *
          git commit -m "Latest data: ${$(date -u)}" || exit 0
          git pull
          git push