name: run_get_youtube_data_to_repo

on:
  workflow_dispatch:

permissions:
  contents:
    write

jobs:
  build:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5

      - name: install uv project dependencies
        run: |
          uv sync --locked --all-extras --dev

      - name: retrieve API credential
        run: |
          cat ${{ secrets.YOUTUBE_API_CREDENTIAL }} | base64 -di > ./backend/pipelines/youtube_api/raw/key.json

      - name: get data
        run: |
          uv run ./backend/pipelines/youtube_api/raw/get_youtube_data_to_repo.py --key_file_path ./backend/pipelines/youtube_api/raw/key.json

      - name: commit and push
        run: |
          git add -A
          timestemp=$(date -u)
          git commit -m "Latest data: ${timestemp}" || exit 0
          git pull
          git push