name: run_get_youtube_data_to_repo

on:
  workflow_dispatch:
    branches:
      - main

permissions:
  contents:
    write

env:
  TARGET_FILE_PATH: ./backend/pipelines/youtube_api/raw

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    run-name: ${{ steps.get-time.outputs.date }}

    steps:
      - uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5

      - name: install uv project dependencies
        run: |
          uv sync --locked --all-extras --dev

      - name: get time
        id: get-time
        run: |
          echo "date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
          echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"

      - name: retrieve API credential
        run: |
          echo ${{ secrets.YOUTUBE_API_CREDENTIAL }} | base64 -d > "$TARGET_FILE_PATH/key.json"

      - name: stage - get data
        run: |
          uv run "$TARGET_FILE_PATH/get_youtube_data_to_repo.py" --key_file_path "$TARGET_FILE_PATH/key.json"

      - name: commit
        run: |
          git config --global user.email coffee-operator-github-action@gmail.com
          git config --global user.name coffee-operator-github-action
          git add --all
          git commit -m "Latest data: $GITHUB_OUTPUT" || exit 0

      - name: pull & push
        run: |
          git pull
          git push